### PR TITLE
Improve index creation from scratch

### PR DESCRIPTION
**Pull request by tristan-morris**
Great repo! I was able to get up and running within a few hours. 

I've added few changes and minor improvements. These are really focused around decreasing the adoption curve. It also might help with #21 and progress on #6.

- Added a quickstart guide. Initially I found myself a bit lost trying to figure out what was needed to start and which components needed what data. I was shooting for functional docker build/images without running it natively on my host.
- Added a docker-compose.yaml which stitches everything together. 
- Changed `airmail_import_osm` allowing for `--pelias-url` to be specified, removing the dark magic of docker container creation within the rust code and hard edges where files are expected to be located. This was very broken in my slightly cursed environment. 
- A few minor clippy suggestions/changes which showed up in the code I was working on. 
- A few minor formatting changes so I could better read the code.

Do you have a docker hub repo if you were interested in pushing the images?

### CODE REVIEW

**Comment by ellenhp** [comment]
Great work! If we're going to take a dependency on docker-compose/podman-compose for indexing I think we should break the dependency on `bollard` and remove all of the logic to start the spatial server docker container from the indexer. It shouldn't be too hard to rip it all out, but if you'd like I can do that as a follow-up because these changes do look cohesive and good overall. Removing bollard means less complexity but it also means no more docker-in-docker nonsense which has been a problem because the docker/podman socket isn't always in the same location.

If you do break the dependency on bollard, you'll be able to remove the docker socket bind mount in the compose files too.

Minor nit-pick: Pelias is a different geocoder, what we're using from the project is an experimental system that they built a while ago called the spatial server which is different from pelias itself so I don't want to call its base url `pelias_url`.

**Comment by tristan-morris** [comment]
Perfect! I'll make the suggested changes and thanks for the clarification on pelias, I thought it didn't quite fit but now it makes sense.

I'll include a separate change with `bollard` and the dind capability removed - happy to do it. 

Sounds good re ghcr. It was more for better container naming in the compose. I'd imagine most use-cases someone would create an index and be done with it, whereas larger users would likely have some kind of custom pipeline to integrate anyway. 

I came across your repo from a Reddit post months ago which I starred and planned to come back to. Now I'm looking to include both forward and reverse geocoding in my stack (pure rust) and evaluating options. I like where this is at and what you're looking to do, so happy to contribute.

**Comment by ellenhp** [comment]
I'd love to add reverse geocoding at some point. People do seem to want it. It should be as simple as just looking up a set of s2 cells in the index then doing post-processing on the returned docs to sort them exactly by distance.

**Comment by tristan-morris** [comment]
Awesome!! It would be neat. I might take a look at it later in the week(?).

7b81765 removes the dind function. I've left in the CLI parm for specifying the path to the wof database, as this could also be incorporated into the indexing component at some stage?

**Comment by tristan-morris** [comment]
I have created a separate branch on my fork `spatial` which replaces the spatial container/server with rust native wof sqlite queries.

Performance wise, it's pretty much the same (docker makes this 5-10x slower, similar to the spatial container version). Indexing is ~45-50k POIs/s. I tested a few implementations based on futures, without async, parallel readers and a connection pool. They're pretty similar but the current connection pool approach appears to be the most stable CPU wise. According to some dirty flamegraphs the slowest points seem to centre around indexing, loading and cache lookups now. Interestingly CPU load decreases over time as does the parsing speed. 

The implementation utilises a r2d2 connection manager and rusqlite. One downside I don't like but it seems to be the normal approach is it requires the `libsqlite3-mod-spatialite` package/sqlite extension. But you can pretty much run a few binaries and you have a functional geocoder :)

image

**Comment by ellenhp** [comment]
Very cool. I'm ok taking a hard dependency on a spatialite module if there's a docker image for those on weird distros without it packaged, and Windows users and stuff.

Currently indexing of ways is very slow because we calculate the centroid. I've been meaning to quantize all of the points in the way to s2 cells then iff they're all quantized to the same cell do a lookup for just that cell, otherwise fall back on the centroid calculation. From the profiling I did I suspect this would speed things up.

I'm going to review this PR soon. There are some regional English differences in the documentation but I'm not going to send you a bunch of nit comments to "fix" them. Very excited about these contributions!

Another thing to look at once the spatialite changes are upstreamed is doing spatialite queries in the server itself. I'd absolutely love to be able to return shapes for admin area queries instead of just a center point. Center point isn't useful if I type "Australia" into a geocoder. Even a bounding box isn't really what I want for that query. Having spatialite on the server is also useful for coarse reverse geocoding points in the middle of nowhere. There won't be any indexed features in the middle of nowhere but it would be nice to at least provide the administrative area hierarchy.

Quick question: Are you planning on running from block storage or over an HTTP connection?

**Comment by tristan-morris** [comment]
Awesome. I've merged in the native wof code. 

Haha sounds good re the review and Australian/British english vs American. It's tricky hey! I try to catch myself in international codebases but forget in docs most of the time. 

So, I realised I messed up the profiling and why the rust wof code was virtually the same speed as the node implementation (I expected some change), it was based on pre-cached data. Uncached is around 10-15k/pois/s, not 50k. I did have a look at the centroid calculation as well and what you suggested could help. I tried a channel approach to offload/parallelise the calculation and see what effect it had, and overall execution time was pretty similar. There's a small improvement in switching from malloc to mimalloc as my profiles showed quite a lot of alloc calls - I think this is really just a side effect of loading all of the POIs etc. from osmx. 

Exactly my thinking for the bbox approach and reverse geocoding. It's those little engineering quirks which help make it useful!

My usecase is one needing to do both forward and reverse geocoding. For a given point or polygon, determine towns/regions close by/nearest. And forward is the typical usecase. I'll likely host the index on Cloudflare R2 or S3 on k8s and query with a remote index (depends on perf - R2 is a bit slow here I find for too many range queries...). 

Currently I'm checking to see if I can improve some of the wof lookups as I don't like the node library is faster at the moment.

**Comment by ellenhp** [comment]
Sounds good. I'm not sure if you caught it from the website but HTTP indices are very slow. The demo is down so you can't see for yourself but I'm talking generally under 10s latency, 1-2s latency common if the cache is hot. I'd generally recommend hosting the index with a web server on a VPS that can pull the data directly from a local disk. That'll be way faster than object storage and you can still scale sub-linearly because lots of airmail instances can share one index host. R2 is the very slow (but very cheap) option. I don't have numbers on latency characteristics of lower-latency HTTP indices, so that's something you'll have to test out.

Another consideration is that Airmail enables the quickwit feature on tantivy for remote indices which switches the termdict to be sstable-based instead of fst-based. High level this makes access patterns sequential instead of random (extremely helpful if you're fetching 2mb chunks every time you get a fault a 4kb page), but it essentially rules out any possibility of performant typo-tolerant queries.

The reason this is on my mind is because taking an optional dependency on spatialite in airmail_service means allocating a nontrivial amount of local storage per instance just for the WOF database (35gb as of today). I don't have a planet index on my workstation currently but if I remember right it's in the low hundreds of gigabytes, so about one order of magnitude larger than the WOF database.

When the local disk space requirements were more like 500mb vs 300gb (approx) it was compelling to offload onto object storage for use-cases where poor latency doesn't matter. 35gb vs 300gb is a lot less compelling.

**Comment by tristan-morris** [comment]
I've had a really mixed time with HTTP ranged requests querying remote indices/files. Even with optimised cog geotiff, which was kind of built for the purpose. It breaks down really quickly, one user requesting 16 256x256 tiles for an area, and each tile requires 5-6 requests to fetch the tile data is a bad user experience. But with other formats it's been amazing. 

It's why geo stuff is kind of interesting right, it's the worst of all worlds. I guess including sqlite + spatialite for indexing is a slightly different problem, as you need the local space to build the index anyway. But incorporating it into the core part of the geocoder can be pretty beneficial. I guess one approach is essentially having features on/off depending on user requirements? Then users can opt-in.

Another option potentially worth considering (depending how deep you want to go...), is to rip the useful information out of the sqlite database (polygons, places and properties - at the moment), and store it directly in novel geo structures to query at runtime. For instance, pull out the polygon data, store it in a R-Tree, extract associated data etc. This might hit the small (fits on a node easily), performant, but more complexity - this doesn't solve 'search' more broadly haha.

**Comment by tristan-morris** [comment]
Some more updates... I'm thinking a bit about my deployment and how it'll all fit together. Apart from forward and reverse geo, it would be neat to be able to maintain a separate index for stuff interesting to my own services/users. This separate index would need to be updated/re-created every few minutes - pretty straight forward, but I'm keen to ensure the import process is rock-solid. 

I hope you don't mind that I've added these into this branch/PR. But hopefully they'll help to progress the safety, performance and reliability of airmail too. The last thing I'm trying to crack for this PR is improving the performance of the PIP code.

Updates:
- Standardise error handling with anyhow and thiserror to avoid unexpected panics. Removing most unwraps and expects in indexing and related code. I will look at the service code too, just need to ensure there aren't any unexpected panics when running in prod... :)
- Reduce some async executor starvation.
- Switch to sqlx from rusqlite, for perf.
- Merge import and index project files, as the concerns are dependent. This might be contentious (so I'm sorry if it is!) but I struggled constantly to find the indexer/import main code.). Currently there's now the airmail lib, indexer related code, and the service. 
- Cleanly terminate import process, terminating all child tasks. e.g. ctrl+c and it dies.

Rough perf notes:
Using R2D2 SQLite, sync default, journal default, pool size = max physical, main importer worker count = all
[2024-07-24T22:50:20Z INFO airmail_indexer::importer] 1780000 POIs parsed in 316 seconds, 5627.248985045054 per second.

Using R2D2 SQLite, sync off, journal wal, pool size = max physical, importer worker count = all
[2024-07-24T22:56:41Z INFO airmail_indexer::importer] 1770000 POIs parsed in 260 seconds, 6793.537725653552 per second

Using R2D2 SQLite, sync off, journal wal, pool size = all cpus, importer worker count = all
[2024-07-24T23:02:11Z INFO airmail_indexer::importer] 1770000 POIs parsed in 305 seconds, 5786.769726327416 per second.

Using R2D2 SQLite, sync off, journal wal, pool size = physical, importer worker count = physical
[2024-07-24T23:12:25Z INFO airmail_indexer::importer] 1770000 POIs parsed in 243 seconds, 7254.268044496302 per second.

Using SQLx, pool = physical, worker = physical
[2024-07-24T23:19:44Z INFO airmail_indexer::importer] 1770000 POIs parsed in 267 seconds, 6628.422913329843 per second.

WTF - Flamegraph runs faster
[2024-07-25T00:04:08Z INFO airmail_indexer::importer] 1780000 POIs parsed in 232 seconds, 7672.089567886623 per second.

Using R2D2, rusqlite, release
[2024-07-25T00:24:27Z INFO airmail_indexer::importer] 1780000 POIs parsed in 236 seconds, 7536.300938360011 per second.

With SQLx, rw database debug = 1 in release? This makes no sense.
[2024-07-25T00:29:45Z INFO airmail_indexer::importer] 1770000 POIs parsed in 203 seconds, 8707.955521146809 per second.

I have no idea why, but when running with flamegraph, it's even faster. what on earth.
[2024-07-25T04:32:42Z INFO airmail_indexer::importer] 1770000 POIs parsed in 189 seconds, 9338.917903036392 per second

Flamegraph is roughtly 60-70% mod_spatialite (point-in-polygon) processing. The load queue is kept full, indexing and caching are empty. I'm thinking about a better pip implementation...

**Comment by ellenhp** [comment]
Is this ready for review? At some point where you're at a good stopping point I'll make time to review and merge. I noticed that the source branch for this PR is `main` which might cause fun problems post-merge due to divergence, but we can cross that bridge when we get there. As long as it's not substantially slower than before I'm fine with being bottlenecked on PIP queries. Indexing in airmail is already crazy fast compared to a lot of other geocoders so I don't think it's a huge issue.

**Comment by tristan-morris** [comment]
Ok awesome. I've renamed the branch so it'll make merging easier (I didn't realise it'd close this PR). What I might do is finish off this tranche I'm working on and submit it as a new PR when it's ready. It's definitely a bit bigger than I thought originally... But hopefully it helps the project overall.

I've managed to improve/fix the pip query speed, with a an _optional_ r-tree index. The tradeoff is the pip index takes ~5 minutes to build and 10GB of memory, but it's ~2x faster than the pip sqlite queries. 

I'm just running a planet import to see how it goes. I think it's in the ways loading step as it seems single thread CPU constrained. Otherwise the Australia region takes 75 seconds :) Planet is 28820000 POIs parsed in 19492 seconds, 1478.5547875774112 per second.

**Comment by ellenhp** [comment]
That makes sense, just keep me posted. I've spot-checked your work and it's solid, I'll review it even if it's a huge PR though I may not get to it right away. There may be some back-and-forth but I don't have any major objections so far. Like what am I going to do, ask you to put the unwraps back in? 🤣 

I noticed you removed the separation between the indexer crate and the OSM importer, which seems fine to me but I want to make sure you don't do anything that will make it harder to index OpenAddresses and (eventually) TIGER data.

**Comment by tristan-morris** [comment]
Haha I mean, I could put them back in. I think most things I've worked on are dual purpose, if it's 11/10 stable then confidence improves, but it also makes it easier to maintain and improve on. And selfishly, it also makes it easier to integrate with as well. I was also thinking about why the demo might be dead too...

I kind of hope that might be the most controversial change. I noticed the deps were pretty much identical and thought most future use cases would consist of indexing + loading one source or another, but you wouldn't ordinarily index or load in isolation. So adding a new source would likely be adding some new args, dedupe code and reusing everything - and hopefully it's a bit simpler and easier to manage too. 

I'm super relaxed at reviews either way 😀 please take your time.

**Pull request closed without merging**
